apiVersion: v1
kind: Namespace
metadata:
  name: telegraf-injector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-injector
  namespace: telegraf-injector
  labels:
    app: telegraf-injector
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: telegraf-injector
  labels:
    app: telegraf-injector
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: telegraf-injector
  labels:
    app: telegraf-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf-injector
subjects:
- kind: ServiceAccount
  name: telegraf-injector
  namespace: telegraf-injector
